NAME = fract-ol
CC = cc -g
CFLAGS = -Wall -Wextra -Werror -Lminilibx-linux -lmlx_Linux -lX11 -lXext -o
SRC_DIR = ./src
OBJ_DIR = ./obj
MLX_DIR = ./minilibix-linux
MLX = $(MLX_DIR)/mlx.a

SRC = $(SRC_DIR)/events.c \
      $(SRC_DIR)/fractol_utils.c\
	  $(SRC_DIR)/init.c \
	  $(SRC_DIR)/main.c \
	  $(SRC_DIR)/math_utils.c \
	  $(SRC_DIR)/render.c \

OBJ = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRC))

INCLUDE = $(MLX_DIR)/mlx.h \
		  $(SRC_DIR)/fractol.h

all: libs $(NAME)

libs:
		make -C $(MLX_DIR)

$(NAME): 	$(OBJ)
			$(CC) $(CFLAGS) $(OBJ) -L$(MLX_DIR) -lft -o $(NAME)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c $(INCLUDE) Makefile
				mkdir -p $(OBJ_DIR)
				$(CC) $(CFLAGS) -c $< -o $@

clean:
		$(MAKE) -C $(MLX_DIR)
		rm -rf $(OBJ_DIR)

fclean: clean
		$(MAKE) -C $(MLX_DIR) fclean

re: fclean all

.PHONY: all clean fclean re